spring:
  docker:
    compose:
      enabled: false
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_PROJECT_ID}
          location: europe-west4
          chat:
            options:
              model: gemini-1.5-flash
              temperature: 0.2
            enabled: true
          embedding:
            options:
              model: text-embedding-004
            enabled: true

slack:
#  signingSecret: ${SLACK_SIGNING_SECRET}
  botTokenA: ${SLACK_BOT_TOKEN_A}
  botTokenB: ${SLACK_BOT_TOKEN_B}
  broadcastChannel: ${BROADCAST_CHANNEL}
whatsapp:
  verifyToken: ${VERIFY_TOKEN}
  apiUrl: ${WHATSAPP_API_URL}
  accessToken: ${WHATSAPP_ACCESS_TOKEN}
  phoneNumberId: ${WHATSAPP_PHONE_NUMBER_ID}



